name: Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'

      - name: npm install and build hexo
        run: | 
           npm install yarn -g
           yarn install
           yarn build 
        env: 
           CI: true 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          publish_dir: ./public
   
